### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by DataNinja100** [MrCrayfish/Framework#11]
Ok, so I play controller on java, but I also use replay mod and fabric optifine, however, the game crashes when I try to play the 3 mods together.

I would really appreciate it if you were able to fix this :)

**Comment by AshleyRosemarry** [comment]
Yeah, I literally just started troubleshooting my mods for this, as the moment I putt in Framework it crashed. There seems to be an issue with Optifine, at least for 1.20.1, cuz even with forge, keeps crashing.

I would also really appreciate a fix for the compatibility, cuz I really wanna play with controller, but I cannot play w/o Optifine. I even made an entire account just to comment here lol. Thanks.

**Comment by VulpesStella** [comment]
> Ok, so I play controller on java, but I also use replay mod and fabric optifine, however, the game crashes when I try to play the 3 mods together.
> 
> I would really appreciate it if you were able to fix this :)

Use sodium & iris instead of optifine on Fabric.

**Comment by DataNinja100** [comment]
Thanks

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
