### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by Kameli1** [MrCrayfish/Framework#13]
Im trying to open the game with the gun mod and framework 0.4.2 and it just crashes every time when i open it but it doesn't without the framewrok!
![Näyttökuva 2024-02-03 220534](https://github.com/MrCrayfish/Framework/assets/156953263/f2c77699-8b12-48eb-9d05-032e06ac46c7)

**Comment by EclipseofLife** [comment]
put your crash report bruh

**Comment by MrCrayfish** [comment]
Please attach the crash report

**Comment by WendigoWasTaken** [comment]
Aight i know the problem its because your Forge Modloader version isnt the newest one or the one required just click the 3 dots next to play, open profile options and under advanced settings you'll see "Current Modloader Version" just put in the newest one and you'll be good to go.

**Comment by MrCrayfish** [comment]
Closing this issue due to no response. If you would like the issue reopened, please post a new issue with the crash report attached. Thank you.
