### ISSUE TITLE
Client hangs up with this being the last error that occurred

### ISSUE THREAD

**Issue by FrozenGalaxy** [MrCrayfish/Framework#14]
Log: https://gist.github.com/FrozenGalaxy/c1e8d53ae4290720e1cff04c5d469281

Not sure what's happening here

**Comment by EclipseofLife** [comment]
I am also getting this and similar errors quite often. Sometimes the "bound" is different for me.

**Comment by JacquePott** [comment]
I've been getting the same. Just started happening out of nowhere after a couple of weeks. Now I can't get my save running without removing Framework.

**Comment by MrCrayfish** [comment]
Thanks for the report. This has now been fixed in the latest update.
