### ISSUE TITLE
[1.20.1] Framework 0.6.26 requires Forge at least 4.2.0 or higher Neoforged is only at 4.1.99  for the latest version

### ISSUE THREAD

**Issue by jamieb999** [MrCrayfish/Framework#15]
So I updated my Framework to Framework 0.6.26 and it says that it requires 
Forge 4.2.0 or higher there is no Neoforged 4.2.0 the latest version 
as of today's date (February 14 2024) is 4.1.99 which is what I am running.
of Neoforged for 1.20.1. 

This is the error I get in my latest.log 

[14Feb.2024 00:08:11.134] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'forge', Requested by: 'framework', Expected range: '[47.2.0,)', Actual version: '47.1.99'
[14Feb.2024 00:08:12.793] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[14Feb.2024 00:08:12.801] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[14Feb.2024 00:08:13.901] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[14Feb.2024 00:08:19.519] [main/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §eframework§r requires §6forge§r §o47.2.0 or above§r
§7Currently, §6forge§r§7 is §o47.1.99

https://neoforged.net/

![image](https://github.com/MrCrayfish/Framework/assets/115375746/1f2345b9-96cc-4385-afc9-db979376c23f)

Now on Curseforge it is listing Framework 0.6.26 as the latest version for 1.20.1 
but by the sounds of it you really need 1.20.2 or higher for it. because it will not work. 

[https://www.curseforge.com/minecraft/mc-mods/framework/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1](https://www.curseforge.com/minecraft/mc-mods/framework/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1)

[https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.99/forge-1.20.1-47.1.99-installer.jar](https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.99/forge-1.20.1-47.1.99-installer.jar)

Please either fix the sites and fix the information for this mod or fix the mod itself
so that it actually with Neoforged 4.1.99 

DO NOT tell me to run Forged either no one is running forged any more 
Forged is dead the whole team left Lex and no one is running it
any more Neoforged has the support of pretty much most of the 
mod creators out there. 

FORGE is DEAD Neoforged is the current fork everyone is running! 

Fix your mod!  This is most definately a bug with the mod either make it work with Neoforged 4.1.99 or don't list 
it as the latest version for Forge 1.20.1 because most people out there are running NeoForged now. 

All the developers left LexManos and forked off Neoforged and Neoforged has the support of pretty much most of
the mod developers out there. Forge is gone bury it and be done with it. 

Now please fix your mod so it works with Neoforged 4.1.99 please or list it for 1.20.2 or higher. 

And no I won't run Forge after LexManos and his transphobia towards trans people so don't 
even ask me! 

If your not going to support Neoforged then I will cease using your mods because Neoforged
has the support of pretty much most of the mod creators out there. 

[https://medium.com/@aislinnbmullen/minecraft-modding-and-bigotry-35cbd255479](https://medium.com/@aislinnbmullen/minecraft-modding-and-bigotry-35cbd255479)

"It came to light recently that LexManos had been displaying transphobic behavior — that is, liking, 
following, and retweeting transphobic posts and individuals on Twitter."

Logs can be seen at 
[https://paste.debian.net/hidden/8f151dae/](https://paste.debian.net/hidden/8f151dae/)

Also due to Framework 0.6.26  it is creating a crash log as well which can be seen bellow
[https://paste.debian.net/hidden/30ca8372/](https://paste.debian.net/hidden/30ca8372/)

All of this is related to your mod!  Please fix it. 

Running on a Debian 12 server  I run here (64 bit) 

 uname -a
Linux server2.homenet.darkshado.local 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

And no I can up upgrade to 1.20.2 or higher because I have a good number of 
mods that only support 1.20.1 so I can not upgrade to 1.20.2 or higher. 

For now I guess I will be forced to downgrade to Framework Framework 0.6.16 (Aug 22 2023)
but please fix the mod so it is set on curse forge and other sites for 1.20.2 or higher so that 
way it doesn't bug me all the time saying there is an update for this mod when there really isn't
unless you fix the mod to work properly with neoforged 4.1.99

[https://www.curseforge.com/minecraft/mc-mods/framework/files/4718251](https://www.curseforge.com/minecraft/mc-mods/framework/files/4718251)

**Comment by MrCrayfish** [comment]
Framework is not supported and won't be available for NeoForge on Minecraft 1.20.1 regardless of the compatibility (non-guaranteed) that NeoForge advertised. Only Minecraft 1.20.4 and higher is official supported.

**Comment by jamieb999** [comment]
That is horrible everyone runs NeoForge and FORGE is dead. Fix your mod saying that it won't be made available on 1.20.1 is unacceptable.  Fix your mod immediately! 

You are just too lazy to fix your mod this is what happens when you have amateurs coding mods that
don't know what they are doing you end up with messed up mods like this. 

If you are not going to support 1.20.1 then fix Curseforge and other repositories 
modrinth.com so that Framework 0.6.26  is not listed as the latest for version 1.20.1

Because it simply will NOT work with 1.20.1 and Framework 0.6.26. 

This is NOT completed what so ever wow you are a horrible developer if you just 
close off the issue without even doing something what a horrible developer.

I will definatley never recommend that anyone run any of your mods! 
What an absolutely horrible developer!  that refuses to fix their mod that is
broken and simply closes off the ticket and dismisses it immediately without
even looking into the issue. Horrible developer!

**Comment by Gcat101** [comment]
No

**Comment by JaisDK** [comment]
There are 0 packs running NeoForge because it's not possible to do so. Saying everyone is running Neo is just plain wrong. If you want mods that are not tagged as Neo to run in your installation then make it work yourself by changing the jar file instead of whining and complaining about modders not taking the time out of their busy schedule to run double support.

After you've put in some minimum amount of effort yourself, then go jump into a hole and bury yourself for the behavior you've displayed today towards someone who is putting in their valuable time to make something for other for free for you to enjoy.

**Comment by DerCommander323** [comment]
> That is horrible everyone runs NeoForge and FORGE is dead. Fix your mod saying that it won't be made available on 1.20.1 is unacceptable. Fix your mod immediately!

-1.20.1 NeoForge is also "dead"
-Whats there to fix? It supports exactly what both of the mod providers say it supports.

> You are just too lazy to fix your mod this is what happens when you have amateurs coding mods that don't know what they are doing you end up with messed up mods like this.

Ok smarthead, if you have an IT degree anyways, why don't you do it? You clearly seem to know everything about Minecraft modding anyways, so it should be easy!

> If you are not going to support 1.20.1 then fix Curseforge and other repositories modrinth.com so that Framework 0.6.26 is not listed as the latest for version 1.20.1

0.6.26 simply is the latest version for 1.20.1, again, what's there to fix?

> Because it simply will NOT work with 1.20.1 and Framework 0.6.26.

Works as advertised and intended.

> This is NOT completed what so ever wow you are a horrible developer if you just close off the issue without even doing something what a horrible developer.

It is completed, and they did do something. They told you there will not be NeoForge support on 1.20.1.

> I will definatley never recommend that anyone run any of your mods! What an absolutely horrible developer! that refuses to fix their mod that is broken and simply closes off the ticket and dismisses it immediately without even looking into the issue. Horrible developer!

-definatley is not a real word
-_You do realize that noone actually takes you seriously, right? We can see all the other ridiculous issues you've made, where you've proven that you are not a good person with opinions that noone should even be forced to listen to._
-The mod _still_ isn't broken, it supports exactly what it says it supports.
