### ISSUE TITLE
`entity.sync.SyncedEntityData.hasSyncedDataKey` caused crush

### ISSUE THREAD

**Issue by LTCatt** [MrCrayfish/Framework#18]
[crash-2024-05-03_01.48.30-server.txt](https://github.com/MrCrayfish/Framework/files/15192941/crash-2024-05-03_01.48.30-server.txt)
[crash-2024-05-03_02.59.02-server.txt](https://github.com/MrCrayfish/Framework/files/15192943/crash-2024-05-03_02.59.02-server.txt)

It seems that creating an entity randomly causes crashes :/

Version: Forge 1.20.1-0.6.27

**Comment by LTCatt** [comment]
I'm sorry but is there any plan for fixing this?

**Comment by MrCrayfish** [comment]
If you update to 0.7.6 it should now be fixed.
