### ISSUE TITLE
Framework version required by Goblin Traders 1.20.4 not on Curseforge

### ISSUE THREAD

**Issue by Gamemassa** [MrCrayfish/Framework#19]
Hi, I just added the 1.20.4 version of Goblin Traders to my custom modpack and I got an error message saying I needed to update Framework to 0.7.4 or above, but the latest version of Framework for MC 1.20.4 available on your Curseforge page is Framework 0.7.3 so I can't actually use Goblin Traders.

**Comment by MrCrayfish** [comment]
Sorry about that. Just uploaded it, Fabric version might not be available immediately but you can download it from my website if it's not available yet. [https://mrcrayfish.com/mods/framework/files](https://mrcrayfish.com/mods/framework/files)

**Comment by Gamemassa** [comment]
Oh cool! Thanks!
