### ISSUE TITLE
Mod crashes on new NeoForge 1.20.6 builds

### ISSUE THREAD

**Issue by ModernGamingWorld** [MrCrayfish/Framework#21]
![2024-05-25_20 11 24](https://github.com/MrCrayfish/Framework/assets/75923060/c0d0dc81-856d-44e6-bb85-259b9cd66cb5)

**Comment by MrCrayfish** [comment]
I'll look into this soon. NeoForge are still making breaking changes until they produce a stable release, so very likely any mod, not just mine will break.

**Comment by MrCrayfish** [comment]
Thanks for the report. This has now been fixed.
