### ISSUE TITLE
Something about versions 0.6.27, cause reload bugs for 1.20.1 ports of forks for Gun mod

### ISSUE THREAD

**Issue by ribs498** [MrCrayfish/Framework#25]
I have made a fork of the gun mod, for 1.20.1, for framework versions past 0.6.27, an issue occurs when dying, reloading gets stuck, various debugging and testing seems like its not anything i can do on my end, im not sure if there is anything i can provide to help

**Comment by MrCrayfish** [comment]
I'll look into the issue. I may have unintentionally broken some logic.

**Comment by ribs498** [comment]
Id Appreciate it!

**Comment by MrCrayfish** [comment]
Good news, I have found the issue. Should have a patch out soon. 

Edit: Currently still trying to create a solution. More trivial than first expected.

**Comment by MrCrayfish** [comment]
Alright, so the issue was due to incorrectly copying data. Fix can be viewed here: https://github.com/MrCrayfish/Framework/commit/a03672dc9f98c8d584b572d104e375894da31f85
