### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by King-Tulip** [MrCrayfish/Framework#3]
Everytime I load a modpack with framework, it always says that it needs a version of forge that I can't find, and also it says it needs to be in the 1.19 version, but I'm playing in 1.16, so is there a way to still play it on 1.16? How do I fix this?

**Comment by MrCrayfish** [comment]
Framework is for 1.18.2 and above. If you are trying to use the Gun Mod or Vehicle Mod you need to use Obfuscate
