### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KostromDan** [MrCrayfish/Framework#4]
I was flying on a plane abount 15 minutes, then game crashed.
[crash-2022-07-29_21.07.35-server.txt](https://github.com/przemykomo/simple-planes/files/9222402/crash-2022-07-29_21.07.35-server.txt)
[latest.log](https://github.com/MrCrayfish/Framework/files/9222536/latest.log)

I've wrote to simpleplanes mod author, he says that the crush is form this mod.
https://github.com/przemykomo/simple-planes/issues/123

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/Framework/commit/44ea69fa74cfe7ec2933106509ee3a95c00859df. I'll have a release soon!
