### ISSUE TITLE
Minecraft crashes when loading with Controllable mod

### ISSUE THREAD

**Issue by haolun7788** [MrCrayfish/Framework#9]
Version: 1.20.1 - forge-47.10
Mod in question: https://www.curseforge.com/minecraft/mc-mods/controller-mod/files/4453027

Framework is a dependency of controllable

Crashes whenever I boot up Minecraft and spits out error code 1. Crashes when Framework and Controllable are booted at the same time.

**Comment by haolun7788** [comment]
Update: Works fine without optifine, crashes when optifine HD_U_15 is also enabled

**Comment by MrCrayfish** [comment]
This is a Controllable issue, not Framework.
